#######################################################################
##
##   nome do script yaml: ansible-deploy-nocpro2_auto.yml
##   descricao: Este script foi feito para atualizar o nocPro2_auto nos Pops
##   autor: marcos.rodrigues
##   email: marcos.rodrigues@terceiro.rnp.br
##   data de criacao: 25/06/2021.
##   chamado de criacao/motivo: N/A  (fazer o deploy do codigo nocPro2_auto
##   versao 1.0
##
##########################################################################

---
- hosts: '{{ host }}'
  remote_user: '{{ user }}'

  become: True
  any_errors_fatal: True
  tasks:
      - name: " 1° Adicionando o diretorio nocPro2_auto em /usr/share/centreon/ "
        synchronize:
            src:  nocPro2_auto/..
            dest: /usr/share/centreon/
            recursive: yes
            delete: yes
            compress: yes
            perms: yes
            rsync_opts:
                 - "--exclude=.git"
                 - "--exclude=ansible-deploy-nocpro2_auto.yml"
                 
      - name: " 2° Trocando o owner do diretorio e a permissao de arquivos"
        file:
            path: /usr/share/centreon/TESTE-ANSIBLE-JEKINS
            group: '{{ group_app }}'
            owner: '{{ owner_app }}'
            mode: '0750'
            recurse: yes
